name: Build and publish

env:
  RELEASE_VERSION:

on:
  repository_dispatch:

jobs:
  windows-build:
    name: Windows
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        run: |
          Invoke-WebRequest -Uri "https://github.com/adang1345/PythonWin7/raw/master/3.12.1/python.3.12.1.nupkg" -OutFile "python.3.12.1.nupkg"
          mkdir "C:\custom_python"
          nuget install python -Source $(Get-Location) -OutputDirectory "C:\custom_python\"
          echo "C:\custom_python" >> $GITHUB_PATH
          echo "C:\custom_python\Scripts" >> $GITHUB_PATH
          python --version

      - name: Set up libraries
        run: |
          python -m pip install wheel poetry
          python -m pip install "https://github.com/pcroland/Pyinstaller-Builds/releases/download/PyInstaller/pyinstaller-6.3.0-py3-none-win_amd64.whl"
          python -m pip install .

      - name: Fetch version
        run: |
          $version=$(python -c "print(open('changelog.md', 'r').read().split('\n')[0].split(' ')[2].replace(':', ''))")
          echo "Version: $version"
          echo "RELEASE_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Build
        run: |
          python -m pyinstaller -F __main__.py -n deew --icon logo/icon.ico

      - name: Move dist/deew.exe to deew.exe
        run: mv dist/deew.exe deew.exe

      - name: Workflow finished
        run: echo "Workflow finished."
